### ISSUE TITLE
Subclassable resolvers

### ISSUE THREAD

**Issue by pauxus** [flyway/flyway#1567]
Currently, we have an option to skipDefaultResolvers, allowing us to completely replace the used resolvers. However, most of the time, when replacing the default resolvers, we actually want only to tweek the behaviour of them (for example: use a different strategy for caculating the versions, such as encoding part of the version in the directory name) (see also #1183 and #1185)

This is currently rather ugly, because we need to copy and paste a lot of code from the default resolvers.

I propose a couple of changes in order to make this easier. The main goal of these changes is to allow to subclass the default resolvers in order to prevent copy and paste (of course, since the default resolvers are not official API, such custom subclasses need to be tied to specific flyway versions to be guaranteed to work):

- [x] #1566 This is a first step. When creating a custom resolver, only one instance is created, while for the default resolvers, one instance is created for each location. I moved the locations loop inside the resolvers. This does not change the behaviour, but is a necessary step to allow to replace a default resolver with a custom subclass
- [x] Let the default resolvers use an empty constructor. For this, three steps are needed: (partially in #1570)
  - [x] let them take the data needed from the flywayConfiguration (#811) object injected into them. (previously implement in [5b7bfd9]) (#1569)
  - [x] We need a different way to inject the Scanner into the default resolvers. This could work via a separate setter or some other mechanism (#1568)
  - [x] Remove usage of `DbSupport` in `SqlMigrationResolver` altogether. The Resolver and Executor do not really need it, they simple hand it down to SqlScript, which could always create a matching DbSupport object using the jdbcTemplate's connection during `execute()`. This would result in a lot more DbSupport objects being created (which are cheap, but could be - if necessary - negated by caching the `DbSupport` objects with their connection as `WeakReference` in `WeakHashMap`). Also, now the parsing of the scripts would be done during the actual execution of the migration, not at resolving time (this could also be prevented by giving`SqlScript`access to the`FlywayConfiguration` object)
- [ ] documentation update and testcase. These really only make sense for the issue as a whole, since most changes are internal only and thus covered by the existing tests. However, once the issue is resolved, all a test case and documentation for the feature (replacing a resolver with a custom subclass) need to be provided.

Two more tasks which would make this even more useful (just to show where I am headed with this):
- Provide some methods of the default resolvers as protected, to allow overriding specific methods (Usecase for us: Parse the migration version not only from the filename, but also from the folder structure : 1.4_new_Feature/5_procedures/V1.2__demo_procedure --> 1.4.5.1.2)
- JdbcResolver and SpringJdbcResolver are almost identical. By extracting a common superclass, we could make it a lot easier to support similar frameworks.

**Comment by pauxus** [comment]
@axelfontaine Can you agree with this direction and intention? I already implementend that completely once, we need this feature, so I will reimplement it, but I would prefer not to do it a third time. We went with a custom patched version for the last two years, but I'd like to stay with the default version if possible - especially since a know of a couple of other projects which have also expressed interest in that functionality.

Do you see any showstoppers or problems in the general approach?

**Comment by MalikKillian** [comment]
I definitely feel this should be categorized **Soon-Definitely**.  A very basic script executor, reusing 90% original code, took me a couple of days to write and test.  And since so many objects had to be recreated (e.g. Database, ResourceProvider, SqlStatementBuilderFactory, CallbackExecutor, etc.) a lot of overhead is introduced and the likelihood of an update breaking our resolver is greatly increased.

**Comment by axelfontaine** [comment]
@MalikKillian Can you please describe your usecase in detail as to why you need a custom resolver?

**Comment by dougrahn** [comment]
@axelfontaine We have a scenario where we have an HA cluster with two databases.  The solution requires that we execute all of the commands to the primary database, but not all to the secondary as some types of commands will sync across because of the HA solution while others don't.  The oddity of this make it so that we want to prevent certain commands from being executed.  We found we can do this with a custom sql script executor, but want to use the default resolver.  In other words, we would like to make a sub class to the resolver where the only code change is while executor it uses.  We can't do this while everything is private.

**Comment by pauxus** [comment]
@axelfontaine Our original use case was to tune how the version number is parsed while retaining the complete other logic. 

For example to take the version from the folder names instead of only the filename, which might get quite large otherwise:

/13/5/124/v18.4__bla.sql -> 13.5.124.18.4 

This is still doable with the current approach.

However, we had a different requirements (extremely large and complex database, we are talking about multiple terabytes): The developers wanted to automatically set the schema according to a specific place in the folder structure, which is not availabe using the current system. 

i.e. 
5/15/1__core/v10__bla.sql -> 5.15.1.10 executed against "CORE"
5/15/2__office/v10__bla.sql -> 15.15.2.10 executed against "OFFICE"

This takes away a lot of risk with missed "ALTER SESSION" statements.

It is also not doable using a custom resolver, because that would need to have access to some details (don't remember which, right now).

With my changes this was extremely easy to implement.

However, after having reimplemented the changes 3 times almost completely (and never getting an answer about the approach except closed PRs) - I have in the meantime left that project and returned to more traditionell Databases (still using flyway). So I am quite reluctant to put any more effort into this - altough there seems to be still a demand.

**Comment by pauxus** [comment]
I also implemented a Groovy Executor a while back, which made good use of that functionality. IMHO Groovy is a perfect language for Code based migrations (think Sql-class).

**Comment by nigredo-tori** [comment]
+1 to this issue. When I needed to add some postprocessing to resolved migrations (turn the transaction on/off depending on the transaction name), I had to collect a non-trivial amount of code to wire together an `SqlMigrationResolver` identical to the one that is built by default. Since this code uses internal abstractions, it's obviously brittle - but the only other way would be to reimplement the whole thing from scratch.

Even worse, turns out that some of these abstractions are tricky to use. For example,  a `Database` built using `DatabaseFactory.createDatabase` does not always close the underlying `java.sql.Connection` on `.close` - which, apparently, is [not a bug](https://github.com/flyway/flyway/issues/2262) :man_facepalming: . I ended up doing a magical `database.getMainConnection()` to work around this.

For my use case, just adding some kind of `Function<MigrationResolver, MigrationResolver>` for post-processing the default resolver would be enough, but I see that this would be kind of messy.

**Comment by MikielAgutu** [comment]
@nigredo-tori Would the new [Script Config File option `executeInTransaction` ](https://flywaydb.org/documentation/scriptconfigfiles) help with this?

@pauxus @dougrahn Flyway has changed a fair bit since you first requested this. Do you still need it? If so, can you explain your use case? Also, what changes would you like to see in the code as it stands today to make this work?

**Comment by nigredo-tori** [comment]
@MikielAgutu, yes, that looks like it does exactly what I need, so I would be able to eliminate that hack. Thank you.

**Comment by MikielAgutu** [comment]
@pauxus @dougrahn Any news?

**Comment by pauxus** [comment]
@MikielAgutu As said, I have left the project where we had that particular requirement - as far as I know they are still using my patched version based on an old flyway version. However the use the commercial edition, so one day this might resurface...

While I still think that this would be a very useful change, I frankly don't see any point in wasting more time on it. Therefore feel free to close this.
